outofbound:
	mkdir -p build
	g++ source/outofbound.cpp -o build/outofbound
	./build/outofbound

integeroverflow:
	mkdir -p build
	g++ source/integeroverflow.cpp -o build/integeroverflow
	./build/integeroverflow

bufferoverflow:
	mkdir -p build
	g++ source/bufferoverflow.cpp -o build/bufferoverflow
	./build/bufferoverflow

memoryleaking:
	mkdir -p build
	g++ source/memoryleaking.cpp -o build/memoryleaking
	./build/memoryleaking