test:
	mkdir -p build
	g++ source/test.cpp -o build/test

file:
	mkdir -p build
	g++ source/file.cpp -o build/file
	./build/file

process:
	mkdir -p build
	g++ source/process.cpp -o build/process
	./build/process